#182461142 - USERS SHOULD BE ABLE TO FOLLOW EACH OTHER
Skaehub-Technologies/speaksfer-dragon-x-bend pull request #30
Opened 2022-07-28 10:41 UTC by ChrisOnsando

#### What does this Pull Request do?
- [ ] Users are able to follow and unfollow each other
#### Description of Task to be completed?
- [ ] Users should be able to follow and unfollow each other
- [ ] Users should be able to see their followers and following
#### How should this be manually tested?
- [ ] N/A
#### Any background context you want to provide?
- [ ] Users should follow and unfollow users they wish
#### What are the relevant Pivotal Tracker story?
- [ ]  https://www.pivotaltracker.com/story/show/182461142
#### Screenshots (if appropriate)
- [ ] N/A
#### Questions:
- [ ] None

2022-07-28 12:07 UTC, mainamuriuki274 requested changes

2022-07-28 12:07 UTC, mainamuriuki274 commented on app/user/models.py
> +    id = models.UUIDField(
I told you to remove this field

2022-07-28 12:07 UTC, mainamuriuki274 commented on app/user/tests/test_views.py
> +    @property
remove this decorator

2022-07-29 07:57 UTC, ChrisOnsando commented on app/user/models.py
> +    id = models.UUIDField(
Change made

2022-08-01 07:47 UTC, mainamuriuki274 requested changes

2022-08-01 07:47 UTC, mainamuriuki274 commented on app/user/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
also assert that the user is in the followers list

2022-08-01 07:47 UTC, mainamuriuki274 commented on app/user/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
assert that the user is no longer in the followers list

2022-08-01 07:47 UTC, mainamuriuki274 commented on app/user/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)
assert for the expected message also

2022-08-01 07:47 UTC, mainamuriuki274 commented on app/user/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
How is this one 201 and the user is unauthorized???? don't just write tests for the sake

2022-08-01 07:47 UTC, mainamuriuki274 commented on app/user/tests/test_views.py
> +        self.user_one = User.objects.create_user(
Check on this

2022-08-01 07:47 UTC, mainamuriuki274 commented on app/user/tests/test_views.py
> +        self.user_two = User.objects.create_user(
Check on this

2022-08-02 13:03 UTC, dalienst commented
PR is ready to be merged

2022-08-03 05:43 UTC, mainamuriuki274 approved these changes

2022-08-03 05:44 UTC, merged