182913315 - USER SHOULD BE ABLE TO HIGHLIGHT ON ANY TEXT IN AN ARTICLE AND MAKE COMMENTS
Skaehub-Technologies/speaksfer-dragon-x-bend pull request #40
Opened 2022-08-10 07:39 UTC by dalienst

#### What does this Pull Request do?

- enable user to highlight text and make comments on it

#### Description of Task to be completed?

- POST: api/articles/highlight/
- GET: api/articles/highlight/
- PATCH: api/articles/highlight/
- DELETE: api/articles/highlight/<highlight_id>/

#### How should this be manually tested?

- Using postman, login user and test every endpoint stated above

#### Any background context you want to provide?

- Ability of user to highlight on a text and comment on it.
- Ability of user to reference their highlight when they need to

#### What are the relevant pivotal tracker?

- [182913315](https://www.pivotaltracker.com/n/projects/2570600/stories/182913315)

#### Screenshots (if appropriate)
![Screenshot from 2022-08-08 15-39-12](https://user-images.githubusercontent.com/88655199/183842669-133815c9-4eb1-427b-b50d-260f4b4e040b.png)

![Screenshot from 2022-08-08 15-39-27](https://user-images.githubusercontent.com/88655199/183842796-0a844814-65fd-4eaf-8e35-2f12b4397869.png)

![Screenshot from 2022-08-08 15-47-31](https://user-images.githubusercontent.com/88655199/183842901-5a377ddd-6005-468d-9c52-bd6ae6b3b313.png)

#### Questions:

- N/A

2022-08-10 09:03 UTC, ChrisOnsando reviewed
Changes made on the PR

2022-08-10 11:56 UTC, mainamuriuki274 requested changes

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/models.py
> +    highlight_id = models.UUIDField(
Create abstract class

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/models.py
> +    highlight_start = models.PositiveIntegerField(null=True, blank=True)
remove null and blank =True

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/models.py
> +    highlight_text = models.TextField(blank=True, null=True)
remove null and blank true

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/serializers.py
> +        queryset=Article.objects.all(), slug_field="slug"
use id instead of slug for lookup

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/serializers.py
> +    highlight_start = serializers.IntegerField(min_value=0, required=False)
it needs required

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/serializers.py
> +    highlight_end = serializers.IntegerField(min_value=0, required=False)
it needs required

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/serializers.py
> +        if not data.get("highlight_start") and data.get("highlight_end"):
remove this

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/serializers.py
> +        if validated_data.get("highlight_start") and validated_data.get(
remove this

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/serializers.py
> +            if start and end:
if not required

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/serializers.py
> +                    if start < end
use if statement

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/serializers.py
> +                    if start < end
if start > end:
    start, end = end, start

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/tests/test_views.py
> +    def test_highlight_text_in_an_article_without_specifying_limits(
??

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
assert message

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
response.json()

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
assert message

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
assert message

2022-08-10 11:56 UTC, mainamuriuki274 commented on app/articles/tests/test_views.py
> +        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
assert message

2022-08-11 06:18 UTC, dalienst commented on app/articles/models.py
> +    highlight_id = models.UUIDField(
Okay

2022-08-11 06:19 UTC, dalienst commented on app/articles/models.py
> +    highlight_start = models.PositiveIntegerField(null=True, blank=True)
Done

2022-08-11 06:20 UTC, dalienst commented on app/articles/models.py
> +    highlight_text = models.TextField(blank=True, null=True)
Done

2022-08-11 06:28 UTC, dalienst commented on app/articles/serializers.py
> +        queryset=Article.objects.all(), slug_field="slug"
Done

2022-08-11 06:29 UTC, dalienst commented on app/articles/serializers.py
> +    highlight_start = serializers.IntegerField(min_value=0, required=False)
Done

2022-08-11 06:29 UTC, dalienst commented on app/articles/serializers.py
> +    highlight_end = serializers.IntegerField(min_value=0, required=False)
Done

2022-08-11 06:35 UTC, dalienst commented on app/articles/serializers.py
> +        if not data.get("highlight_start") and data.get("highlight_end"):
Done

2022-08-11 06:50 UTC, dalienst commented on app/articles/serializers.py
> +        if validated_data.get("highlight_start") and validated_data.get(
Done

2022-08-11 06:51 UTC, dalienst commented on app/articles/serializers.py
> +                    if start < end
Done

2022-08-11 14:36 UTC, mainamuriuki274 approved these changes

2022-08-11 14:36 UTC, merged